[project]
name = "allegro-fireflyiii"
version = "0.2.0"
description = "Sample project with cz bump"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0"
tag_format = "v{version}"
version_files = ["pyproject.toml"]
update_changelog_on_bump = true
